### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by mominbuet** [smurn/jsift#1]
I want to use this library for a research, Any tutorial or the main program of this project?

**Comment by smurn** [comment]
Feel free to use the code!

Unfortunately, I've never got around finishing it. If memory serves, I've only implemented the first steps of the SIFT algorithm. I think the gaussian pyramid is implemented and the first step of the key point locator, but the filtering steps and the descriptor extraction are missing.

The unit tests should give you the best overview of what is there and how it is to be used.

I have no plans to continue working on this project at the moment, but if you decide to pick the project up I'll try to answer questions you may have about the code.

-Stefan
