### ISSUE TITLE
How to run the code and where to provide input images

### ISSUE THREAD

**Issue by vishalezen** [smurn/jsift#2]
I am a newbie to java image processing and I want SIFT descriptors of images.
But as in this repository there is no any main method neither in main package nor in the test.
How to use the code. Where to provide image an input. Please reply.
Thank you so much.

**Comment by alexeygrigorev** [comment]
+1

**Comment by alexeygrigorev** [comment]
As far as I can see, [tests](https://github.com/smurn/jsift/blob/master/src/test/java/org/smurn/jsift/ExtremaDetectorTest.java) can be quite helpful - but nevertheless it would be nice to have some examples

**Comment by vishalezen** [comment]
@alexeygrigorev  Thank you so much for the reply.

**Comment by smurn** [comment]
Thank you for your interest. This project is incomplete and no longer in development. It's only about half a SIFT implementation. Feel free to pick it up and finish it, but there are other implementations out there that actually work. OpenCV is available for Java, for example.
